 <div id="footer" class="wrapper clearfix">
    <div class="left">
		<div>
			<a href="http://facebook.com/letsdoitworld"><img src="<?php print base_path() . path_to_theme(); ?>/images/96/facebook.png" /></a>
			<a href="http://youtube.com/letsdoitworld"><img src="<?php print base_path() . path_to_theme(); ?>/images/96/youtube.png" /></a>
			<a href="http://twitter.com/letsdoitworld"><img src="<?php print base_path() . path_to_theme(); ?>/images/96/twitter.png" /></a>
			<a href="http://flickr.com/groups/letsdoitworld"><img src="<?php print base_path() . path_to_theme(); ?>/images/96/flickr.png" /></a>
			<a href="http://letsdoitworld.stumbleupon.com"><img src="<?php print base_path() . path_to_theme(); ?>/images/96/stumbleupon.png" /></a>
		</div>
      <h2>Join our newsletter</h2>
    <a href="http://t.co/2IAO1XpQ">December</a> | <a href="http://t.co/cq0pbQAR">November</a> | <a href="http://t.co/I8ZPn4Gd">October</a> | <a href="http://t.co/8j3fO2eU">September</a> | <a href="http://t.co/cnLa4p9">August</a> | <a href="http://bit.ly/ldinews7">July</a> | <a href="http://bit.ly/ldinews5">May</a> | <a href="http://bit.ly/ldinews3">March</a> | <a href="http://bit.ly/ldinews2">February</a> | <a href="http://t.co/GOd1frJ1">Mapping</a> <br/>  
	  <?php include 'newsletter.inc' ?>
	</div>
    <div class="right">
      <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fletsdoitworld&amp;width=292&amp;colorscheme=light&amp;show_faces=true&amp;stream=false&amp;header=false&amp;height=242" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:242px;" allowTransparency="true"></iframe>
    </div>
  </div>
  <!-- //footer -->  
  
  