<div style="width:100%; display:block; padding: 10px 0;" class="clearfix">
	<div style="float:left;">
		<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="letsdoitworld">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
	</div>
	<div style="float:left;">
		<div id="fb-root"></div>
		<script src="http://connect.facebook.net/en_US/all.js#appId=209536922422914&amp;xfbml=1"></script>
		<fb:like href="" send="true" width="450" show_faces="false" font=""></fb:like>
	</div>
</div>